First release

diff --git a/volumio2/berryboot-init b/volumio2/berryboot-init
--- a/volumio2/berryboot-init
+++ b/volumio2/berryboot-init
@@ -1,1 +1,380 @@
+#!/bin/busybox sh
+
+# Source & license at https://github.com/macmpi/berryboot-scripts
+# Feel free to report any issue or comment there.
+
+
+### This file resides in Volumio read-only squashfs image
+# This script does Volumio backoffice supervisor stuff, similarly to Volumio original init
+# It is run by berryboot init BEFORE aufs overlay filesystem is composed
+#
+# Note: it is run under Berryboot busybox, with root privileges
+# this script is inlined into berryboot init, so be careful about variables, cd, ...
+#
+# we can use (but shall not modify) the following variables:
+#
+# IMAGE=`cat /tmp/answer`
+# DATADIR="/mnt/data/$IMAGE"
+# SHAREDDIR="/mnt/shared"
+# IMAGEPATH="/mnt/images/$IMAGE"
+# GOVERNOR
+
+ENTRYPATH=$(pwd)     # we are now safe to eventually change directory
+
+
+############## Self-patch init sequence and relaunch from next banner ##################
+# Required until https://github.com/maxnet/berryboot/pull/437 is resolved
+# berryboot-init is inlined into /init, but the file resides in /squashfs.
+# Therefore, while running, it prevents un-mounting squashfs image and then update image.
+# So the trick here is to relaunch this script (and following part of init) from another
+# location, hence exiting/freeing this original file...  (circumvoluted?  humm... yes! :p)
+
+echo ""
+echo "Prepping script relocation..."
+
+# we construct relocated all-in-one init script
+echo "#!/bin/busybox sh" > /reloc-init
+# we keep this script from next banner to execute beyond that point
+sed -n -e '/^#* We start from here !! #*/,$p' /squashfs/berryboot-init >> /reloc-init
+# we append the remaining part of inird
+sed -n -e '/^.*# Fedora and Arch symlink.*/,$p' /init >> /reloc-init
+chmod 770 /reloc-init
+
+# we need to make sure our new /reloc-init can access insofar variables we (and init) need
+export IMAGE
+export DATADIR
+export SHAREDDIR
+export IMAGEPATH
+export GOVERNOR
+export ENTRYPATH
+
+echo "Now we will continue from another location... see you soon !!"
+exec /reloc-init   # exec ensures we keep PID 1, which is required for switch_root
+
+# now we are gone in hyperspace !!!
+
+
+###################### We start from here !! ###########################
+
+BBINITVERSION="1.0"
+
+# due to wget https limitation in berryboot:
+# https://github.com/maxnet/berryboot/issues/439
+# we need http only, so we can not link to github for now....
+# will be redirected to Github as soon as possible
+BBINITURL="http://bit.do/BBInitV2"    
+INSTV2URL="http://bit.do/InstV2"      
+
+
+echo "
+######################################################
+########### Volumio2 Berryboot Integration ###########
+###########    version  ${BBINITVERSION}   by macmpi    ###########
+"
+
+
+################ generic log utiliy function ###################
+# Display a message and aggregate it for volumio2 journalctl
+VLOGFILE="/data/Vlog.txt"   # Volumio2 OS will consume it
+
+print_msg() {
+  echo "$1" | tee -a /mnt"${VLOGFILE}"
+}
+
+
+########### detect Partitions devices  ######################
+
+# boot partition may not be set by berryboot install in cmdline.txt: that is dangerous!
+BOOT_PART=""
+CMDLINE=$(cat /proc/cmdline)
+
+for p in ${CMDLINE};
+do
+  key=${p%%=*}
+  value=${p#*=}
+  
+  case $key in
+  bootdev)
+    BOOT_PART=$value    # does not include /dev name part
+    ;;
+  esac
+done
+
+# sanity-check
+if [ -z "${BOOT_PART}" ]; then
+  echo "
+WARNING !!!  Please check & edit bootdev= statement in cmdline.txt on your
+Berryboot boot partiton. cmdline.txt MUST have a proper bootdev definition
+statement:   bootdev=mmcblk0p1 or =sda1 or other relevant boot partition
+Device will now halt in few seconds"
+  sync
+  umount /mnt
+  sleep 10
+  halt -f
+else
+  BOOT_PART="/dev/${BOOT_PART}"
+fi
+
+
+# Berryboot data partiton (always exists at this point) may not be directly the one specified in
+# cmdline.txt by datadev= , namely in case of complex mounts such as encrypted partitions or iSCSI
+# so we look at which device corresponds to /mnt currently, as berryboot has completed it's own mounting work here
+# in case of encrypted partitions, fstab mount requires mount by UUID, so we always use it
+DATA_PART=$(df | egrep "/mnt" | awk '{print $1}')
+
+print_msg "Partitions found:  boot: ${BOOT_PART}   berryboot data: ${DATA_PART}"
+
+########### Sanity-checks finished #######
+
+
+
+#############################################################
+############## Volumio Reset & Updates functions ############
+#############################################################
+BOOTMOUNT="/boottemp"    # temp /boot mount
+mkdir -p "${BOOTMOUNT}"
+mount -t vfat -w "${BOOT_PART}" "${BOOTMOUNT}"
+
+
+################# Reset data section ##############################
+# Now we deal with eventual factory reset & al
+# currently we do not do factory image save/reload; we just keep previous image
+# so factory and user data reset are same
+# Note: this has to be very-first as it wipes overlay: NO DATADIR setup stuff before this!
+# Follow-up sections should do all initial overlay setup
+
+# if there is factory or user reset files then format data partition
+if [ -e "${BOOTMOUNT}"/factory_reset ] || [ -e "${BOOTMOUNT}"/user_data ]; then
+  rm "${BOOTMOUNT}"/factory_reset "${BOOTMOUNT}"/user_data > /dev/null 2>&1
+  rm -rf "${DATADIR}"
+  print_msg "Factory reset successfully executed"
+fi
+
+
+################# Volumio Updates section ##########################
+# Now we setup things so that Volumio2 built-in differential updates work.
+# We check if such update has been done previously, in order to replace image.
+# Note: after update we relaunch new-image script with it's own script do new own setup
+# so we stay away from any significant changes before doing update (do that first after reset)
+
+BBMOUNT="/berryboot"
+mkdir -p "${DATADIR}${BBMOUNT}"  # create mount point in overlayfs
+
+
+# setting-up /imgpart directory (within overlay) that receives OS updates from Volumio app.
+UPDTDIR="${DATADIR}/imgpart"
+if [ ! -d "${UPDTDIR}" ]; then
+  mkdir -p "${UPDTDIR}"
+  chmod 777 "${UPDTDIR}"
+fi
+
+
+# discard eventual kernel updates as Berryboot runs its own kernel
+if [ -e "${BOOTMOUNT}"/kernel_update ]; then
+    rm "${BOOTMOUNT}"/kernel_update
+fi
+
+
+# Manage Volumio squash image updates
+if [ ! -h "${UPDTDIR}"/volumio_current.sqsh ]; then
+  if [ -f "${UPDTDIR}"/volumio_current.sqsh ]; then
+  
+    # if the update failed before completion
+    if [ -e "${BOOTMOUNT}"/update_process ]; then
+      print_msg "Image update attempt failed, keeping current image"
+      rm "${BOOTMOUNT}"/update_process
+    else
+      print_msg "Installing updated image"
+      cd "${UPDTDIR}"
+      # we try to get latest patches from network or fallback with existing ones
+      if ! wget -O berryboot-init "${BBINITURL}" > /dev/null 2>&1; then
+        cp /squashfs/berryboot-init .
+      fi
+      chmod ug+x berryboot-init   # needed because we will relaunch with exec command, not inline
+      print_msg "Patching updated image"
+      if mksquashfs ./berryboot-init volumio_current.sqsh > /dev/null 2>&1; then
+        print_msg "Unmounting previous image and replacing with new"
+        umount -f /squashfs  # we are now running from /reloc-init so we should be safe to keep running!...
+        mv -f volumio_current.sqsh "${IMAGEPATH}"
+        rm -rf "${UPDTDIR:?}"/*
+        umount "${BOOTMOUNT}"
+        rmdir "${BOOTMOUNT}"
+        sync
+        clear
+        print_msg "Mounting Updated image ${IMAGE}"
+        mount -o loop,ro "${IMAGEPATH}" /squashfs
+        cd "${ENTRYPATH}"
+        print_msg "Relaunching with updated image & init..."
+        exec /squashfs/berryboot-init   # exec ensures we keep PID 1
+      else
+        print_msg "Patching new image failed, keeping current image"
+      fi
+    fi    
+    rm -rf "${UPDTDIR:?}"/*
+  fi
+
+  # We link Volumio image into /imgpart to (re)enable zsync differential updates again
+  ln -s "${BBMOUNT}"/images/"${IMAGE}" "${UPDTDIR}"/volumio_current.sqsh    # ${BBMOUNT} to be mounted at Volumio startup
+  print_msg "Ready to accept eventual Volumio2 updates to come..."
+fi
+
+umount "${BOOTMOUNT}"
+rmdir "${BOOTMOUNT}"
+
+
+##################################################################
+############    General config for Volumio2 OS boot   ############
+##################################################################
+
+############ fstab cleanup ########
+# Remove eventual /boot mount from original fstab
+# do it at each squashfs mount, as partiton layout may have changed (image update, cloned setup from another media)
+# we do not add /berryboot mounts here because it will fail in case of encrypted Partitions
+# will mount in berryboot-integ service
+
+print_msg "Patching Volumio /etc/fstab to remove original /boot"
+mkdir -p "${DATADIR}"/etc
+sed '/^\/dev\/.*\/boot.*vfat.*/d' /squashfs/etc/fstab > "${DATADIR}"/etc/fstab
+
+
+########### Swap management ###########
+# we patch original /bin/dynswap.sh to relocate swap file at /berryboot/data/volumio_swapfile,
+# and disable dynamicswap.service at startup (path to swap file not mounted yet). It will still be launched
+# (dynamicswap wanted by volumio.service, but after berryboot-integ) after /berryboot partition is available
+# /berryboot/data/volumio_swapfile will be common to any Volumio2 image running under berryboot
+#
+# we add a feature: if /noswap file is present, then we disable swap at all
+
+print_msg "Optimizing swap management"
+mkdir -p "${DATADIR}"/bin
+if [ -e "${DATADIR}"/noswap ]; then
+  echo "#!/bin/sh" > "${DATADIR}"/bin/dynswap.sh
+else
+  sed 's/\/data\/swapfile/\/berryboot\/data\/volumio_swapfile/g' /squashfs/bin/dynswap.sh > "${DATADIR}"/bin/dynswap.sh
+fi
+chmod 774 "${DATADIR}"/bin/dynswap.sh
+
+# disable dynamicswap.service at startup
+mkdir -p "${DATADIR}"/etc/systemd/system/multi-user.target.wants
+touch "${DATADIR}"/etc/systemd/system/multi-user.target.wants/.wh.dynamicswap.service
+
+
+################ berryboot-integ script & systemd service ###################################
+# setup berryboot-integ script and related systemd service to launch berryboot-integ at Volumio OS startup
+# This allows to mount partitions and issue pre-boot berryboot-phase log into system journal
+# We also use it to schedule swap during OS boot as this shall not happen before berryboot partition is mounted
+
+print_msg "Creating Berryboot integration systemd service for Volumio OS"
+
+# berryboot-integ script is always restored in original state
+echo "#!/bin/sh
+
+### This file resides in Volumio image overlay filesystem
+# It is run as root during Volumio OS image startup through Systemd service.
+# As Volumio OS boots from aufs overlayed filesystem, one may modify this file
+# but such changes will have not effect at next boot, as file is restored in original state
+
+# mounting  /berryboot and /boot partitions
+mount -o defaults ${DATA_PART} ${BBMOUNT}
+mount -t vfat -o defaults,utf8,user,rw,umask=111,dmask=000 ${BOOT_PART} /boot
+
+# dump early berryboot-init log file into system journal
+cat  ${BBMOUNT}${VLOGFILE}
+rm  ${BBMOUNT}${VLOGFILE} > /dev/null 2>&1
+" > "${DATADIR}"/berryboot-integ
+
+chmod 774 "${DATADIR}"/berryboot-integ
+
+# Setup related Systemd service: re-build at each boot to prevent eventual changes
+mkdir -p "${DATADIR}"/lib/systemd/system
+echo "[Unit]
+Description = Berryboot integration service
+After=local-fs.target
+Before=dynamicswap.service
+
+[Service]
+Type=simple
+StandardOutput=syslog
+StandardError=syslog
+SyslogIdentifier=berryboot-integ
+User=root
+Group=root
+ExecStart=/bin/sh /berryboot-integ
+
+[Install]
+WantedBy=multi-user.target" > "${DATADIR}"/lib/systemd/system/berryboot-integ.service
+
+# Enable Systemd service
+mkdir -p "${DATADIR}"/etc/systemd/system/multi-user.target.wants
+ln -s /lib/systemd/system/berryboot-integ.service "${DATADIR}"/etc/systemd/system/multi-user.target.wants/berryboot-integ.service > /dev/null 2>&1
+
+
+################ Add installVolumio2 script as bonus #########################
+
+if [ ! -x "${DATADIR}"/home/volumio/installVolumio2 ]; then
+  mkdir -p "${DATADIR}"/home/volumio
+  chown 1000:1000 "${DATADIR}"/home/volumio
+  if wget -O "${DATADIR}"/home/volumio/installVolumio2 "${INSTV2URL}" > /dev/null 2>&1; then
+    chown 1000:1000 "${DATADIR}"/home/volumio/installVolumio2
+    chmod 744 "${DATADIR}"/home/volumio/installVolumio2
+    print_msg "Added installVolumio2 script in volumio home directory"
+  fi
+fi
+
+
+
+#############################################################
+###############         now some FUN  !!!!       ############
+#############################################################
+
+# Now the hard work is done, lets have a bit of fun !!...
+# we will modify that very file within the overlay filesystem: indeed any "edits" to this file
+# from here in overlay filesystem, or from booted Volumio OS will actually have NO effects
+# as it is run earlier in the boot process, directly from read-only squashfs image.
+# One may then write whatever one wants, or even "delete" it to hide it to ones view, as ugly it may look.
+# Volumio Factory reset or User Data reset will restore file in its original state
+
+if [ ! -e "${DATADIR}"/berryboot-init ]; then
+  cat << "EOF" > "${DATADIR}"/berryboot-init
+                      
+  
+                       /\/\/\/\/\/\  
+                      <            >
+                       |          |
+                       |          |
+                       |   _  _   |
+                      -|_ / \/ \_ |-
+                     |I|  \_/\_/  |I|       Change is good.
+                      -|   /  \   |-         You go first.
+                       |   \__/   |
+                       |          |
+                       |          |
+                       |__________|
+                      /___/\__/\___\ 
+                     /     | \|     \ 
+                       /\  |\ | _@|#_
+                      / /\ | \| |   |
+                      \/  / \ / |   |
+                       \_/___/   \_/ 
+
+
+
+
+
+
+
+PS: feel free to write whatever you want here as on a whiteboard:
+    laundry list, poems, ascii drawings,...
+    or you may delete file if you wish.
+EOF
+
+  chmod 666 "${DATADIR}"/berryboot-init
+fi
+
+sync
+cd "${ENTRYPATH}"
+print_msg "Now we can finally boot Volumio2 image..., go!"
+echo ""
+
+# now we follow into the remaining of berryboot init...
 
